### ISSUE TITLE
10.2 GDG Finder app has server 404 error 

### ISSUE THREAD

**Issue by 2000Vlad** [google-developer-training/android-kotlin-fundamentals-apps#269]
Network call returns 404.
2020-07-27 11:20:56.348 2265-2265/com.example.android.gdgfinder E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.gdgfinder, PID: 2265
    retrofit2.HttpException: HTTP 404 
        at com.jakewharton.retrofit2.adapter.kotlin.coroutines.CoroutineCallAdapterFactory$BodyCallAdapter$adapt$2.onResponse(CoroutineCallAdapterFactory.kt:104)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:129)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

I have also tried to put https://developers.google.com/community/gdg/groups/directory.json in the browser and also get 404.

**Comment by PhilipMottershead** [comment]
Looks like they've updated GDG site and have changed how the events are stored this will most likely need a query to someone at google to see if the is a JSON feed to use.

**Comment by PhilipMottershead** [comment]
Created a pull request #320  with proposed changes that fix this issue.

I still need to check code standards. 

To make this work I had to change the filter functionlity to use country as region is no longer included in the region. This might be able to be fixed.
